defaultNamespace: gorizond

helm:
  chart: ./
  values:
    env:
      - name: DB_DSN_HEADSCALE
        value: ${ if hasKey .ClusterAnnotations "gorizond.db.headscale" }${ get .ClusterAnnotations "gorizond.db.headscale" }${ else }postgres://postgres:password@yb-tserver-service.system-gorizond:5433/gorizond_truncate?sslmode=disable${ end }
      - name: DB_DSN_KUBERNETES
        value: ${ if hasKey .ClusterAnnotations "gorizond.db.k3s" }${ get .ClusterAnnotations "gorizond.db.k3s" }${ else }mysql://root:@tcp(k3s-tidb.system-gorizond.svc.cluster.local:4000)/gorizond_truncate${ end }
      - name: GORIZOND_DOMAIN_HEADSCALE
        value: ${ if hasKey .ClusterAnnotations "gorizond.domain.headscale" }${ get .ClusterAnnotations "gorizond.domain.headscale" }${ else }headscale.public.gorizond.io${ end }
      - name: GORIZOND_DOMAIN_K3S
        value: ${ if hasKey .ClusterAnnotations "gorizond.domain.k3s" }${ get .ClusterAnnotations "gorizond.domain.k3s" }${ else }k3s.public.gorizond.io${ end }
      - name: CLUSTER_DOMAIN_HEADSCALE
        value: ${ if hasKey .ClusterAnnotations "gorizond.cluster.domain.headscale" }${ get .ClusterAnnotations "gorizond.cluster.domain.headscale" }${ else }cluster.local${ end }
      - name: CLUSTER_DOMAIN_K3S
        value: ${ if hasKey .ClusterAnnotations "gorizond.cluster.domain.k3s" }${ get .ClusterAnnotations "gorizond.cluster.domain.k3s" }${ else }cluster.local${ end }
      - name: ENABLE_CONTROLLER_GORIZOND
        value: ${ if hasKey .ClusterAnnotations "gorizond.controller.enabled" }'true'${ else }'true'${ end }
      - name: ENABLE_CONTROLLER_BILLING
        value: ${ if hasKey .ClusterAnnotations "gorizond.billing.enabled" }'true'${ else }'false'${ end }