apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: billingevents.provisioning.gorizond.io
spec:
  group: provisioning.gorizond.io
  names:
    kind: BillingEvent
    plural: billingevents
    singular: billingevent
    shortNames:
      - bevt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              enum: [provisioning.gorizond.io/v1]
            kind:
              type: string
              enum: [BillingEvent]
            metadata:
              type: object
            status:
              type: object
              properties:
                type:
                  type: string
                transitionTime:
                  type: string
                  format: date-time
                amount:
                  type: number
                  format: float
                billingName:
                  type: string
      subresources:
        status: {}
