apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: billings.provisioning.gorizond.io
spec:
  group: provisioning.gorizond.io
  names:
    kind: Billing
    plural: billings
    singular: billing
    shortNames:
      - bill
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              enum: [provisioning.gorizond.io/v1]
            kind:
              type: string
              enum: [Billing]
            metadata:
              type: object
            status:
              type: object
              properties:
                balance:
                  type: number
                  format: float
                lastChargedAt:
                  type: string
                  format: date-time
                lastEventId:
                  type: string
      subresources:
        status: {}
