apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.provisioning.gorizond.io
spec:
  group: provisioning.gorizond.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                kubernetesVersion:
                  type: string
            status:
              type: object
              properties:
                provisioning:
                  type: string
                cluster:
                  type: string
                k3sToken:
                  type: string
                k3sVersion:
                  type: string
                headscaleToken:
                  type: string
                namespace:
                  type: string
                lastTransitionTime:
                  type: string
                  format: date-time
  scope: Namespaced
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
    shortNames:
    - gorizond