{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gorizond-cluster-controller.serviceAccountName" . }}
  labels:
    {{- include "gorizond-cluster-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gorizond-cluster-controller.serviceAccountName" . }}-role
  labels:
    {{- include "gorizond-cluster-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gorizond-cluster-controller.serviceAccountName" . }}-rolebinding
  labels:
    {{- include "gorizond-cluster-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gorizond-cluster-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gorizond-cluster-controller.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
