apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gorizond-install-server.fullname" . }}
  labels:
    {{- include "gorizond-install-server.labels" . | nindent 4 }}
data:
  default.conf.template: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            return 200 'OK';
        }
        
        location ~ ^/(?<cattle>[^/]+)/(?<workslace>[^/]+)/(?<cluster>[^/]+)/(?<k3s>[^/]+)/(?<headscale>[^/]+)/(?<version>[^/]+)$ {
            default_type text/plain;
            
            return 200 "
            #!/bin/sh
            set -eu
            echo 'Install tailscale'
            curl -fsSL https://raw.githubusercontent.com/negashev/tailscale-mirror/patch-1/install.sh | sh
            echo 'Install k3s'
            curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$version K3S_URL=https://api-$cluster-$workslace-$cattle.${GORIZOND_DOMAIN_K3S} K3S_TOKEN=$k3s sh -s - --vpn-auth='name=tailscale,joinKey=$headscale,controlServerURL=http://headscale-$cluster-$workslace-$cattle.${GORIZOND_DOMAIN_HEADSCALE}'  --disable-apiserver-lb --kubelet-arg='eviction-hard=memory.available<50Mi,nodefs.available<5%'
            ";
            
            
            add_header Cache-Control "no-store, no-cache, must-revalidate";
            add_header Pragma "no-cache";
        }

    }