defaultNamespace: gorizond

helm:
  chart: ./
  values:
    env:
      - name: GORIZOND_DOMAIN_HEADSCALE
        value: ${ if hasKey .ClusterAnnotations "gorizond.domain.headscale" }${ get .ClusterAnnotations "gorizond.domain.headscale" }${ else }headscale.public.gorizond.io${ end }
      - name: GORIZOND_DOMAIN_K3S
        value: ${ if hasKey .ClusterAnnotations "gorizond.domain.k3s" }${ get .ClusterAnnotations "gorizond.domain.k3s" }${ else }k3s.public.gorizond.io${ end }
    ingress:
      issuer-mail: ${ if hasKey .ClusterAnnotations "cloudflare-email" }${ get .ClusterAnnotations "cloudflare-email" }${ else }admin@gorizond.io${ end }
      annotations:
        kubernetes.io/tls-acme: 'true'
      tls: 
        - hosts:
          - '${ if hasKey .ClusterAnnotations "gorizond.domain.install" }${ get .ClusterAnnotations "gorizond.domain.install" }${ else }gorizond.cluster${ end }'
          secretName: gorizond-install-tls
      hosts:
        - host: ${ if hasKey .ClusterAnnotations "gorizond.domain.install" }${ get .ClusterAnnotations "gorizond.domain.install" }${ else }gorizond.cluster${ end }
          paths:
            - path: /
              pathType: ImplementationSpecific
      